---


- name: install apache package
  hosts: all

  become: true
  tasks:

    - name: install apache package
      yum:
        name: httpd
        state: latest  


    - name: update repository index
      yum:
        update_cache: yes      
